# Generated by Django 5.0.3 on 2024-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cphone", models.CharField(max_length=16, unique=True)),
                ("cemail", models.EmailField(max_length=254, unique=True)),
                ("cfname", models.CharField(max_length=20)),
                ("clname", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ephone", models.CharField(max_length=16, unique=True)),
                ("eemail", models.EmailField(max_length=254, unique=True)),
                ("efname", models.CharField(max_length=20)),
                ("elname", models.CharField(max_length=20)),
                ("ecategory", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tdate", models.DateField()),
                ("caudio", models.FileField(upload_to="")),
                ("ctext", models.TextField(max_length=1000)),
                ("ccategory", models.CharField(max_length=50)),
                ("cpriority", models.IntegerField()),
            ],
        ),
    ]
