# Generated by Django 5.0.3 on 2024-03-17 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_category_tickets_client_tickets_employee_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tickets",
            new_name="Ticket",
        ),
    ]
