# Generated by Django 5.0.3 on 2024-03-17 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_rename_tickets_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="cemail",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="cfname",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="clname",
            new_name="lname",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="cphone",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="ecategory",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="eemail",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="efname",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="elname",
            new_name="lname",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="ephone",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="caudio",
            new_name="audio_ticket",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="ccategory",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="cpriority",
            new_name="priority",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="ctext",
            new_name="text_ticket",
        ),
    ]
