# Generated by Django 5.0.3 on 2024-03-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_rename_cemail_client_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="firstapp.category",
            ),
        ),
    ]
